name = "Yet Another General Modpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0d30ee10d8a2c16f4b65872665bdb7a7c4156c7c501faeaaa346c56507cdbf7a"

[versions]
fabric = "0.9.3+build.207"
minecraft = "1.16.2"
yarn = "1.16.2+build.47"
