name = "The Vanilla+ Pack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0d478de1ee75f3badb63526d73a7fba1513ab2aca73f10593e17c089e213660b"

[versions]
fabric = "0.9.3+build.207"
minecraft = "1.16.2"
yarn = "1.16.2+build.47"
