name = "Yet Another Vanilla+ Pack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e2e644f78c8cf18259354361ab960ae8b4c6b3911378cd7bedb7e5939bbd0710"

[versions]
fabric = "0.9.3+build.207"
minecraft = "1.16.2"
yarn = "1.16.2+build.47"
