name = "Yet Another Vanilla+ Pack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4f82450e2bb4d8bf815fb6fa52a0d1bb70ea0265619dc6e4723e92765618ddf6"

[versions]
fabric = "0.9.3+build.207"
minecraft = "1.16.2"
yarn = "1.16.2+build.47"
