name = "Yet Another Vanilla+ Pack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8c8a8e9c624a99e0239d5093a2683a4d414ed3b538bd22c4d098bfc5d59962ce"

[versions]
fabric = "0.9.3+build.207"
minecraft = "1.16.2"
yarn = "1.16.2+build.47"
