name = "Yet Another General Modpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f90dc72408ccc0ab00039c00a0f4fb02d09a2db9625d70034e3b9156bd97ed0a"

[versions]
fabric = "0.9.3+build.207"
minecraft = "1.16.3"
yarn = "1.16.3+build.11"
