name = "Yet Another General Modpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c9326003db11f3a6911ead4f4efc7184e9f0b80025ac729a732f169fd718ce5c"

[versions]
fabric = "0.9.3+build.207"
minecraft = "1.16.3"
yarn = "1.16.3+build.11"
