name = "Yet Another General Modpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "12aeba7147f67594aadde0749b14e948ecab0d50f2fc3da6e79bf00724568416"

[versions]
fabric = "0.9.3+build.207"
minecraft = "1.16.2"
yarn = "1.16.2+build.47"
