name = "Yet Another Vanilla+ Pack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d52917bd42706f68cda564d0d498e07b45e1b0ac519ea69b0aa48019c367d2da"

[versions]
fabric = "0.9.3+build.207"
minecraft = "1.16.2"
yarn = "1.16.2+build.47"
