name = "The Vanilla+ Pack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b5c4b24d39ffde0b38d8541fe096c297653f009b0db7edde0c1c37adbd1d21be"

[versions]
fabric = "0.9.3+build.207"
minecraft = "1.16.2"
yarn = "1.16.2+build.47"
