name = "The Vanilla+ Pack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0b9798ecec6f627183c6dbfd3eb55e5f294e78a26419ece6495e1a1db86e2f5e"

[versions]
fabric = "0.9.3+build.207"
minecraft = "1.16.2"
yarn = "1.16.2+build.47"
