name = "Yet Another General Modpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bccc31666f2ccadbeefdc52971f8810cc84fe3f37d77872723ca330e75dbc740"

[versions]
fabric = "0.9.3+build.207"
minecraft = "1.16.3"
yarn = "1.16.3+build.11"
