name = "Yet Another Vanilla+ Pack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7e62c66fc2d562cb225a65c822975ad87b0f44c2c7fe56792aaa53790662ec4a"

[versions]
fabric = "0.9.3+build.207"
minecraft = "1.16.2"
yarn = "1.16.2+build.47"
