name = "Yet Another General Modpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1ad13b3014197aa1af3284a1775813166d37ab9ee95e46fd3a0fc8ce344e7d16"

[versions]
fabric = "0.9.3+build.207"
minecraft = "1.16.3"
yarn = "1.16.3+build.11"
