name = "Yet Another Vanilla+ Pack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dc0c2d67e4870ed5029bae7505c60497cd4f013c46e6da7ff7033cf6ee897f44"

[versions]
fabric = "0.9.3+build.207"
minecraft = "1.16.2"
yarn = "1.16.2+build.47"
