name = "Yet Another General Modpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e84bcc923993ae56edc6f05db0aee215926d749b7082e4209c319c510bccbdbc"

[versions]
fabric = "0.9.3+build.207"
minecraft = "1.16.2"
yarn = "1.16.2+build.47"
