name = "Yet Another General Modpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c738e890765695e7054a3e40bc33994a20d5c42a2f41051c9dbe0b156dab9cca"

[versions]
fabric = "0.9.3+build.207"
minecraft = "1.16.3"
yarn = "1.16.3+build.11"
