name = "Yet Another General Modpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "adbc388b221d7e0c5bf27d29d95f3539570ab1bb3e710c167202137ac87a8044"

[versions]
fabric = "0.9.3+build.207"
minecraft = "1.16.3"
yarn = "1.16.3+build.11"
