name = "Yet Another Vanilla+ Pack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "46bf0fb568ae055df35e49fc811be6b5e5e6be315bcbcd53fcce393b8bf5da16"

[versions]
fabric = "0.9.3+build.207"
minecraft = "1.16.2"
yarn = "1.16.2+build.47"
