name = "Yet Another Vanilla+ Pack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "47b9e513a98a50b6afb61fe0f499e1e960c0b8b9739d6ca5937e0cf96d0a2f44"

[versions]
fabric = "0.9.3+build.207"
minecraft = "1.16.2"
yarn = "1.16.2+build.47"
